services:
  - type: web
    name: medpronto-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: npm install && npx tsc
    startCommand: node dist/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:postgresadmin@db.wrltuhhfqaqlrgoiafph.supabase.co:5432/postgres
      - key: SUPABASE_URL
        value: https://wrltuhhfqaqlrgoiafph.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_KLL387pq4FBIC84iuMtx5g_f_y531_d
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        value: https://medpronto-online.vercel.app